### ISSUE TITLE
Syntax highlight in quoted HTML attributes

### ISSUE THREAD

**Issue by mcdado** [textmate/php-smarty.tmbundle#4]
Thanks for recently accepting the updates to the bundle, loving it so far!
I tried looking at the syntax definition unsuccessfully to solve a highlighting problem that I see with in the PHP Smarty Bundle.

![screen shot 2015-05-13 at 14 59 57](https://cloud.githubusercontent.com/assets/898057/7610969/3e0d60ca-f981-11e4-831a-168530321e49.png)

As you can see, inside the double quotes of the href attribute there's a Smarty tag, but it is not being highlighted. Is it something that is achievable?

**Comment by infininight** [comment]
Added, thanks for the note.
